name: buildRP_Qt5.15.17_MinGW64(unavailable)

# 暂不可用，请先使用build_Qt5.15.17_MinGW810_64
# Qt5.15.17官方使用MinGW810_64 OK，本次使用MinGW1520_64_UCRT，暂不可用

on: workflow_dispatch
#on: [push, pull_request]

env:
  QT_VERSION: '5.15.17'
  QT_TYPE: 'static'
  MinGW_VERSION: 'mingw1520_64_UCRT'
  QT_RP: ''

jobs:
  windows_mingw64_static_release:
    runs-on: windows-latest

    steps:
    # 检出本仓库
    - name: Checkout repository
      uses: actions/checkout@v5

    # 检出RedPanda-CPP仓库
    - name: Checkout repository of RedPanda-CPP
      run: |
        cd ..  #Directory: D:\a\buildRedPanda-CPP
        git clone https://github.com/royqh1979/RedPanda-CPP.git

    # 安装 MinGW64
    - name: Setup MinGW64
      run: |
        cd ..  #Directory: D:\a\buildRedPanda-CPP
        curl -L -o x86_64-release-posix-seh-ucrt.7z https://github.com/niXman/mingw-builds-binaries/releases/download/15.2.0-rt_v13-rev0/x86_64-15.2.0-release-posix-seh-ucrt-rt_v13-rev0.7z
        7z x D:\a\buildRedPanda-CPP\x86_64-release-posix-seh-ucrt.7z -oD:\a\buildRedPanda-CPP

    # 安装 Qt
    - name: Setup Qt
      run: |
        cd ..  #Directory: D:\a\buildRedPanda-CPP
        curl -L -o Qt.7z https://github.com/yuanpeirong/buildQt/releases/download/XXX.7z
        7z x D:\a\buildRedPanda-CPP\Qt.7z -oD:\a\buildRedPanda-CPP

    #D:\a\buildRedPanda-CPP\buildRedPanda-CPP    当前目录即仓库目录
    #D:\a\buildRedPanda-CPP                      上级目录，这里当做根目录
    #D:\a\buildRedPanda-CPP\RedPanda-CPP         RedPanda-CPP源代码目录
    #D:\a\buildRedPanda-CPP\mingw64              Qt目录
    #D:\a\buildRedPanda-CPP\6.10.0-static        Qt目录

    # 构建RedPanda-CPP(调用cmd编译脚本)
    - name: Build RedPanda-CPP
      shell: cmd
      run: |
        setlocal
        set QT_VERSION=${{env.QT_VERSION}}
        set QT_TYPE=${{env.QT_TYPE}}
        set MinGW_VERSION=${{env.MinGW_VERSION}}
        set QT_RP=${{env.QT_RP}}
        call D:\a\buildRedPanda-CPP\buildRedPanda-CPP\build\buildRP-mingw64.cmd %QT_VERSION% %QT_TYPE% %MinGW_VERSION% %QT_RP%

    # 打包
    - name: Package binaries
      run: |
        #ls     #D:\a\buildRedPanda-CPP\buildRedPanda-CPP(即仓库目录)
        7z a RedPanda-CPP-Qt${{env.QT_VERSION}}-${{env.QT_TYPE}}-${{env.MinGW_VERSION}}${{env.QT_RP}}.7z ../RedPanda-CPP-Qt${{env.QT_VERSION}}-${{env.QT_TYPE}}-${{env.MinGW_VERSION}}${{env.QT_RP}} -mx=9

    # 上传
    - uses: actions/upload-artifact@v4
      with:
        name: RedPanda-CPP-Qt${{env.QT_VERSION}}-${{env.QT_TYPE}}-${{env.MinGW_VERSION}}${{env.QT_RP}}
        path: RedPanda-CPP-Qt${{env.QT_VERSION}}-${{env.QT_TYPE}}-${{env.MinGW_VERSION}}${{env.QT_RP}}.7z
