name: LLVM-MinGW

on: workflow_dispatch
#on: [push, pull_request]

jobs:
  windows:
    runs-on: windows-latest
    strategy:
      fail-fast: false
      matrix:
        qt_version: ['6.11.1']
        qt_type: ['static']
        compiler_version: ["llvm-mingw17.0.6_64_UCRT", "llvm-mingw22.1.8_64_UCRT"]
        qt_rp: ["", "_RP"]

    steps:

    # 检出本仓库
    - name: Checkout repository
      uses: actions/checkout@v5

    # 检出RedPanda-CPP仓库
    - name: Checkout repository of RedPanda-CPP
      run: |
        cd ..  #Directory: D:\a\buildRedPanda-CPP
        git clone https://github.com/royqh1979/RedPanda-CPP.git

    # 安装 编译器和Qt库
    - name: Setup Compiler and Qt
      shell: pwsh
      run: |
        $qt_v="${{ matrix.qt_version }}"
        $qt_t="${{ matrix.qt_type }}"
        $co_v="${{ matrix.compiler_version }}"
        $qt_r="${{ matrix.qt_rp }}"

        cd ..  #Directory: D:\a\buildRedPanda-CPP

        if ($co_v -eq "llvm-mingw17.0.6_64_UCRT"){
          curl -L -o llvm_mingw1706.7z https://download.qt.io/online/qtsdkrepository/windows_x86/desktop/tools_llvm_mingw1706/qt.tools.win64_llvm_mingw1706/17.0.6-202409091150llvm_mingw1706.7z
          7z x D:\a\buildRedPanda-CPP\llvm_mingw1706.7z -oD:\a\buildRedPanda-CPP
        }
        if ($co_v -eq "llvm-mingw22.1.8_64_UCRT"){
          curl -L -o llvm-mingw.zip https://github.com/mstorsjo/llvm-mingw/releases/download/20260616/llvm-mingw-20260616-ucrt-x86_64.zip
          unzip -q llvm-mingw.zip -d ./
        }

        if (( $qt_v -eq "6.11.1") -and ($co_v -eq "llvm-mingw17.0.6_64_UCRT") -and ($qt_r -eq "" ))
          { curl -L -o Qt.7z https://github.com/yuanpeirong/buildQt/releases/download/Qt6.11.1_rev1/Qt_6.11.1-static-Release_llvm-mingw17.0.6_64_UCRT.7z }
        if (( $qt_v -eq "6.11.1") -and ($co_v -eq "llvm-mingw17.0.6_64_UCRT") -and ($qt_r -eq "_RP" ))
          { curl -L -o Qt.7z https://github.com/yuanpeirong/buildQt/releases/download/Qt6.11.1_rev1/Qt_6.11.1-static-Release_llvm-mingw17.0.6_64_UCRT_RP.7z }
        if (( $qt_v -eq "6.11.1") -and ($co_v -eq "llvm-mingw22.1.8_64_UCRT") -and ($qt_r -eq "" ))
          { curl -L -o Qt.7z https://github.com/yuanpeirong/buildQt/releases/download/Qt6.11.1_rev1/Qt_6.11.1-static-Release_llvm-mingw22.1.8_64_UCRT.7z }
        if (( $qt_v -eq "6.11.1") -and ($co_v -eq "llvm-mingw22.1.8_64_UCRT") -and ($qt_r -eq "_RP" ))
          { curl -L -o Qt.7z https://github.com/yuanpeirong/buildQt/releases/download/Qt6.11.1_rev1/Qt_6.11.1-static-Release_llvm-mingw22.1.8_64_UCRT_RP.7z }
        7z x D:\a\buildRedPanda-CPP\Qt.7z -oD:\a\buildRedPanda-CPP

    # 构建RedPanda-CPP(调用cmd编译脚本)
    - name: Build RedPanda-CPP with ${{ matrix.qt_version }}-${{ matrix.compiler_version }}${{ matrix.qt_rp }}
      shell: cmd
      run: |
        setlocal
        set QT_VERSION=${{ matrix.qt_version }}
        set QT_TYPE=${{ matrix.qt_type }}
        set COMPILER_VERSION=${{ matrix.compiler_version }}
        set QT_RP=${{ matrix.qt_rp }}
        call D:\a\buildRedPanda-CPP\buildRedPanda-CPP\build\LLVM-MinGW.cmd %QT_VERSION% %QT_TYPE% %COMPILER_VERSION% %QT_RP%

    # 打包
    - name: Package binaries
      run: |
        #ls     #D:\a\buildRedPanda-CPP\buildRedPanda-CPP(即仓库目录)
        7z a RedPanda-CPP-Qt${{ matrix.qt_version }}-${{ matrix.qt_type }}-${{ matrix.compiler_version }}${{ matrix.qt_rp }}.7z ../RedPanda-CPP-Qt${{ matrix.qt_version }}-${{ matrix.qt_type }}-${{ matrix.compiler_version }}${{ matrix.qt_rp }} -mx=9

    # 上传
    - uses: actions/upload-artifact@v4
      with:
        name: RedPanda-CPP-Qt${{ matrix.qt_version }}-${{ matrix.qt_type }}-${{ matrix.compiler_version }}${{ matrix.qt_rp }}
        path: RedPanda-CPP-Qt${{ matrix.qt_version }}-${{ matrix.qt_type }}-${{ matrix.compiler_version }}${{ matrix.qt_rp }}.7z

# =============================================================================
# 路径说明
# D:\a\buildRedPanda-CPP\buildRedPanda-CPP         当前目录即仓库目录
# D:\a\buildRedPanda-CPP                           上级目录，这里当做根目录
# D:\a\buildRedPanda-CPP\RedPanda-CPP              RedPanda-CPP源代码目录
# D:\a\buildRedPanda-CPP\Tools\llvm-mingw1706_64   编译器目录
# D:\a\buildRedPanda-CPP\%LLVM-MINGW_VERSION%      编译器目录
# D:\a\buildRedPanda-CPP\6.11.1-static             Qt目录
# =============================================================================