name: MSVC

on: workflow_dispatch
#on: [push, pull_request]

jobs:
  windows:
    runs-on: windows-latest
    strategy:
      fail-fast: false
      matrix:
        qt_version: ['5.15.17', '6.10.0']
        qt_type: ['static']
        compiler_version: ["msvc2022_32", "msvc2022_64"]
        qt_rp: ["", "_RP"]
        exclude:
          - qt_version: '5.15.17'
            compiler_version: 'msvc2022_32'
            qt_rp: "_RP"
          - qt_version: '6.10.0'
            compiler_version: 'msvc2022_32'

    steps:

    # 检出本仓库
    - name: Checkout repository
      uses: actions/checkout@v5

    # 检出RedPanda-CPP仓库
    - name: Checkout repository of RedPanda-CPP
      run: |
        cd ..  #Directory: D:\a\buildRedPanda-CPP
        git clone https://github.com/royqh1979/RedPanda-CPP.git

    # 安装msvc x86
    - name: Add MSBuild_x86 to PATH
      if: ${{ matrix.compiler_version == 'msvc2022_32' }}
      uses: microsoft/setup-msbuild@v2
      with:
        msbuild-architecture: x86
        
    # 安装msvc x64
    - name: Add MSBuild_x64 to PATH
      if: ${{ matrix.compiler_version == 'msvc2022_64' }}
      uses: microsoft/setup-msbuild@v2
      with:
        msbuild-architecture: x64

    # 安装vsdevenv
    - name: Setup vsdevenv
      uses: seanmiddleditch/gha-setup-vsdevenv@master

    # 安装 Qt库
    - name: Setup Qt
      shell: pwsh
      run: |
        $qt_v="${{ matrix.qt_version }}"
        $qt_t="${{ matrix.qt_type }}"
        $co_v="${{ matrix.compiler_version }}"
        $qt_r="${{ matrix.qt_rp }}"

        cd ..  #Directory: D:\a\buildRedPanda-CPP

        if (( $qt_v -eq "5.15.17") -and ($co_v -eq "msvc2022_32") -and ($qt_r -eq "" ))
          { curl -L -o Qt.7z https://github.com/yuanpeirong/buildQt/releases/download/Qt5.15.17_rev0/Qt_5.15.17-static-Release_msvc2022_32.7z }
        if (( $qt_v -eq "5.15.17") -and ($co_v -eq "msvc2022_64") -and ($qt_r -eq "" ))
          { curl -L -o Qt.7z https://github.com/yuanpeirong/buildQt/releases/download/Qt5.15.17_rev0/Qt_5.15.17-static-Release_msvc2022_64.7z }
        if (( $qt_v -eq "5.15.17") -and ($co_v -eq "msvc2022_64") -and ($qt_r -eq "_RP" ))
          { curl -L -o Qt.7z https://github.com/yuanpeirong/buildQt/releases/download/Qt5.15.17_rev0/Qt_5.15.17-static-Release_msvc2022_64_RP.7z }
        if (( $qt_v -eq "6.10.0") -and ($co_v -eq "msvc2022_64") -and ($qt_r -eq "" ))
          { curl -L -o Qt.7z https://github.com/yuanpeirong/buildQt/releases/download/Qt6.10.0_rev0/Qt_6.10.0-static-Release_msvc2022_64.7z }
        if (( $qt_v -eq "6.10.0") -and ($co_v -eq "msvc2022_64") -and ($qt_r -eq "_RP" ))
          { curl -L -o Qt.7z https://github.com/yuanpeirong/buildQt/releases/download/Qt6.10.0_rev0/Qt_6.10.0-static-Release_msvc2022_64_RP.7z }
        7z x D:\a\buildRedPanda-CPP\Qt.7z -oD:\a\buildRedPanda-CPP

    # 构建RedPanda-CPP(调用cmd编译脚本)
    - name: Build RedPanda-CPP with ${{ matrix.qt_version }}-${{ matrix.compiler_version }}${{ matrix.qt_rp }}
      shell: cmd
      run: |
        setlocal
        set QT_VERSION=${{ matrix.qt_version }}
        set QT_TYPE=${{ matrix.qt_type }}
        set COMPILER_VERSION=${{ matrix.compiler_version }}
        set QT_RP=${{ matrix.qt_rp }}
        call D:\a\buildRedPanda-CPP\buildRedPanda-CPP\build\MSVC.cmd %QT_VERSION% %QT_TYPE% %COMPILER_VERSION% %QT_RP%

    # 打包
    - name: Package binaries
      run: |
        #ls     #D:\a\buildRedPanda-CPP\buildRedPanda-CPP(即仓库目录)
        7z a RedPanda-CPP-Qt${{ matrix.qt_version }}-${{ matrix.qt_type }}-${{ matrix.compiler_version }}${{ matrix.qt_rp }}.7z ../RedPanda-CPP-Qt${{ matrix.qt_version }}-${{ matrix.qt_type }}-${{ matrix.compiler_version }}${{ matrix.qt_rp }} -mx=9

    # 上传
    - uses: actions/upload-artifact@v4
      with:
        name: RedPanda-CPP-Qt${{ matrix.qt_version }}-${{ matrix.qt_type }}-${{ matrix.compiler_version }}${{ matrix.qt_rp }}
        path: RedPanda-CPP-Qt${{ matrix.qt_version }}-${{ matrix.qt_type }}-${{ matrix.compiler_version }}${{ matrix.qt_rp }}.7z

# =============================================================================
# 路径说明
# D:\a\buildRedPanda-CPP\buildRedPanda-CPP    当前目录即仓库目录
# D:\a\buildRedPanda-CPP                      上级目录，这里当做根目录
# D:\a\buildRedPanda-CPP\RedPanda-CPP         RedPanda-CPP源代码目录
# D:\a\buildRedPanda-CPP\mingw64              Qt目录
# D:\a\buildRedPanda-CPP\6.10.0-static        Qt目录
# =============================================================================